/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form;

import variabel.VKeterangan;
import variabel.VNilaiRataRata;
import variabel.VPenghasilan;
import variabel.VTanggungan;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.text.DecimalFormat;
import java.util.logging.Level;

/**
 * @author acer
 */
public class Proses extends javax.swing.JFrame {

    /**
     * Creates new form proses
     */
    DefaultTableModel tblProses;

    public Proses() {
        initComponents();
        String[] judul = {"NIS", "Nama", "Kelas", "Nilai Rata-rata", "Tanggungan Orang Tua", "Penghasilan Orang Tua", "Keterangan"};
        tblProses = new DefaultTableModel(judul, 0);
        tblHasil.setModel(tblProses);
        tampilkanTabel(" ");
    }

    private void tampilkanTabel(String kelas) {
        int row = tblProses.getRowCount();
        for (int a = 0; a < row; a++) {
            tblProses.removeRow(0);
        }
        try {
            Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/db_siswa", "root", "");
            //ResultSet rs = cn.createStatement().executeQuery("SELECT * FROM datasiswa");
            String query;
            if (kelas == " ") {
                query = "SELECT datasiswa.nis, datasiswa.nama, datasiswa.kelas, nilaisiswa.nilai_ratarata,"
                        + "datasiswa.tanggungan, datasiswa.penghasilan_ortu, nilaisiswa.hasil "
                        + "FROM datasiswa JOIN nilaisiswa ON datasiswa.nis = nilaisiswa.nis";
            } else {
                query = "SELECT datasiswa.nis, datasiswa.nama, datasiswa.kelas, nilaisiswa.nilai_ratarata,"
                        + "datasiswa.tanggungan, datasiswa.penghasilan_ortu, nilaisiswa.hasil "
                        + "FROM datasiswa JOIN nilaisiswa ON datasiswa.nis = nilaisiswa.nis WHERE datasiswa.kelas = '" + kelas + "'";
            }
            ResultSet rs = cn.createStatement().executeQuery(query);
            while (rs.next()) {
                String data[] = {rs.getString(1), rs.getString(2), rs.getString(3), rs.getString(4), rs.getString(5), rs.getString(6), rs.getString(7)};
                tblProses.addRow(data);
            }
        } catch (Exception e) {
        }
    }

    private void filter(String query) {
        TableRowSorter<DefaultTableModel> tr = new TableRowSorter<DefaultTableModel>(tblProses);
        tblHasil.setRowSorter(tr);

        if (query != " ") {
            tr.setRowFilter(RowFilter.regexFilter(query));
        } else {
            tblHasil.setRowSorter(tr);

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnProses = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblHasil = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        cbKelas = new javax.swing.JComboBox<>();
        btnKeluar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Tabel Rekomendasi Siswa Penerima Beasiswa");

        btnProses.setText("PROSES");
        btnProses.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                btnProsesFocusGained(evt);
            }
        });
        btnProses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProsesActionPerformed(evt);
            }
        });

        tblHasil.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][]{
                        {},
                        {},
                        {},
                        {}
                },
                new String[]{

                }
        ));
        jScrollPane1.setViewportView(tblHasil);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Kelas   :");

        cbKelas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{" ", "IPA", "IPS", "BAHASA"}));
        cbKelas.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbKelasItemStateChanged(evt);
            }
        });
        cbKelas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbKelasActionPerformed(evt);
            }
        });

        btnKeluar.setText("KELUAR");
        btnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKeluarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel1)
                                .addGap(101, 101, 101))
                        .addGroup(layout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(btnKeluar)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel2)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(cbKelas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(btnProses))
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 684, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(49, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addComponent(jLabel1)
                                .addGap(28, 28, 28)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(btnProses)
                                        .addComponent(jLabel2)
                                        .addComponent(cbKelas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnKeluar)
                                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnProsesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProsesActionPerformed
        // TODO add your handling code here:

        try {
            int row = tblHasil.getRowCount();
            for (int i = 0; i < row; i++) {
                String tempA = (String) tblHasil.getModel().getValueAt(i, 3);
                String tempB = (String) tblHasil.getModel().getValueAt(i, 4);
                String tempC = (String) tblHasil.getModel().getValueAt(i, 5);
                double a = Double.parseDouble(tempA);
                double b = Double.parseDouble(tempB);
                double c = Double.parseDouble(tempC);

                VNilaiRataRata.setNilaiRataRata(a);
                VTanggungan.setTanggungan(b);
                VPenghasilan.setPenghasilan(c);

                Rules.hitung_u();
                Rules.hitung_z();

                DecimalFormat df = new DecimalFormat("#########.###");
                double hasildef = Double.parseDouble(df.format(Rules.defuzzifikasi()));
                VKeterangan.setKeterangan(hasildef);
                double keterangan = VKeterangan.getKeterangan();
                double tidakLolos = VKeterangan.tidaklolos();
                double cadangan = VKeterangan.cadangan();
                double lolos = VKeterangan.lolos();
                String desc;

                if (lolos > cadangan && lolos > tidakLolos) {
                    desc = "Lolos";
                    tblHasil.setValueAt(desc, i, 6);
                } else if (cadangan > tidakLolos) {
                    desc = "Cadangan";
                    tblHasil.setValueAt(desc, i, 6);
                } else {
                    desc = "Tidak Lolos";
                    tblHasil.setValueAt(desc, i, 6);
                }

                System.out.println("Nama : " + tblHasil.getModel().getValueAt(i, 1));
                System.out.println("Hasil Fuzzi : " + hasildef);
                System.out.println("Keterangan Value : " + keterangan);
                System.out.println("Keterangan Tidak Lolos : " + tidakLolos);
                System.out.println("Keterangan Cadangan : " + cadangan);
                System.out.println("Keterangan Lolos : " + lolos);
                System.out.println("Nilai Rata2 : " + VNilaiRataRata.getNilaiRataRata());
                System.out.println("Tangungan : " + VTanggungan.getTanggungan());
                System.out.println("Penghasilan : " + VPenghasilan.getPenghasilan());
                System.out.println("Keterangan : " + desc);
                System.out.println("================================");
                System.out.println();

                Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/db_siswa", "root", "");
                int nis = Integer.parseInt(tblHasil.getModel().getValueAt(i, 0).toString());
                String sql = "UPDATE nilaisiswa SET hasil='" + desc + "' WHERE nis = '" + nis + "'";
                cn.createStatement().executeUpdate(sql);

            }

//            tampilkanTabel();
        } catch (Exception e) {
            e.printStackTrace();
            java.util.logging.Logger.getLogger(Proses.class.getName()).log(Level.SEVERE, null, e);
        }

    }

    public void resetValue() {
        VNilaiRataRata.setNilaiRataRata(0);
        VTanggungan.setTanggungan(0);
        VPenghasilan.setPenghasilan(0);
        VKeterangan.setKeterangan(0);
    }

//GEN-LAST:event_btnProsesActionPerformed

    private void btnProsesFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btnProsesFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_btnProsesFocusGained

    private void cbKelasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbKelasActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_cbKelasActionPerformed

    private void cbKelasItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbKelasItemStateChanged
        // TODO add your handling code here:
        String query = cbKelas.getSelectedItem().toString();
//        filter(query);
        tampilkanTabel(query);
    }//GEN-LAST:event_cbKelasItemStateChanged

    private void btnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKeluarActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        Mainpg mainpg = new Mainpg();
        mainpg.setLocationRelativeTo(null);
        mainpg.setVisible(true);
    }//GEN-LAST:event_btnKeluarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Proses.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Proses.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Proses.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Proses.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Proses().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKeluar;
    private javax.swing.JButton btnProses;
    private javax.swing.JComboBox<String> cbKelas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblHasil;
    // End of variables declaration//GEN-END:variables
}
